// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherStreamer.Infrastructure.Data;

#nullable disable

namespace WeatherStreamer.Infrastructure.Migrations.AuditEntries
{
    [DbContext(typeof(WeatherStreamerDbContext))]
    [Migration("20251113034107_CreateAuditEntries")]
    partial class CreateAuditEntries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("WeatherStreamer.Domain.Entities.AuditEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewETag")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrevETag")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SimulationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditEntries", (string)null);
                });

            modelBuilder.Entity("WeatherStreamer.Domain.Entities.Simulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("NotStarted");

                    b.HasKey("Id");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("IX_Simulations_StartTime");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Simulations_Status");

                    b.HasIndex("FileName", "Status")
                        .HasDatabaseName("IX_Simulations_FileName_Status");

                    b.ToTable("Simulations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Simulations_Status", "Status IN ('NotStarted', 'InProgress', 'Completed')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
